#BNF+IAT 1.0 UTF-8;
!grammar wake;
!slot <callCmd>;
!slot <weather1>;
!slot <weather2>;
!slot <weather3>;
!slot <date>;
!slot <limit>;
!slot <temperature>;
!slot <weatherEnd1>;
!slot <weatherEnd2>;
!slot <weatherEnd3>;
!slot <dateEnd>;
!slot <limitEnd>;
!slot <tempStart>;
!slot <tempEnd>;
!start <callStart>;
<callStart>:[<callCmd>]<weather1><weatherEnd1>|[<callCmd>]<weather2><weatherEnd2>|[<callCmd>]<weather3><weatherEnd3>|[<callCmd>]<date>[<dateEnd>]|[<callCmd>]<limit>[<limitEnd>]|[<tempStart>]<temperature>[<tempEnd>];
<callCmd>:今天|今儿|今日;
<weather1>:温度;
<weather2>:气温;
<weather3>:天气;
<weatherEnd1>:怎么样|咋样|多少|情况;
<weatherEnd2>:多少|情况;
<weatherEnd3>:怎么样|咋样|情况;
<date>:星期几|周几|几号|什么日子|日期|多少号;
<dateEnd>:了|呢|呀|啊;
<limit>:限行|限号;
<limitEnd>:情况|是多少|是什么|车辆|车牌|号码|数字;
<tempStart>:现在|当前|此时|此刻;
<temperature>:室温|室内湿度|室内温湿度|环境;
<tempEnd>:多少|几度|情况|怎么样|是多少;
